### ISSUE TITLE
Hyrax Email Notifications for User Activity

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sdr3-planning#1]
Add to Hyrax email notifications for user activity, and have it so that each user can turn off individually, as well as make it a global on/off option.

Uncertain if this something that can be worked in within Hyrax planning now, is already there, or something we want to add to our list of work needs for the upcoming SUL SDR3 Work Cycle. @mjgiarlo do you know?

[source: [2017-07-08 SDR3 Planning Meeting](https://docs.google.com/document/d/1wt2hi6t1Ac8jMStG_egLCXBmJ86F7xBLqXAfaEaXtwE/edit#)]

**Comment by mjgiarlo** [comment]
@cmh2166 Hi! This is most likely to be tackled by our Stanford-based team rather than any community actors for the time being. If we need it for Hydrox, we should include this work in-scope for the Hydrox/SDR3 work cycle. Thanks for asking. :)

**Comment by cmh2166** [comment]
so i'll just leave this here for the time being as a holder for something that needs to be added to that SDR3 / Hyrax or Hydrus developers work cycle.
