### ISSUE TITLE
Add SUL-Branding to SUL Hyku Demo

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sdr3-planning#3]
The demo is going to be styled to be more stanford-y. Needs to occur before being shared out with SUL users for demo testing and feedback.

Who to assign this to? cc: @hannahfrost @mjgiarlo 

[source: [2017-07-08 SDR3 Planning Meeting](https://docs.google.com/document/d/1wt2hi6t1Ac8jMStG_egLCXBmJ86F7xBLqXAfaEaXtwE/edit#)]

**Comment by hannahfrost** [comment]
@ggeisler offered to take this on.

**Comment by mjgiarlo** [comment]
w00t. Thanks, @ggeisler!

**Comment by ggeisler** [comment]
Just noting that I can't do anything related to this until #14 is resolved.
