### ISSUE TITLE
Versioning in Hydrox & SDR3 Decisions Needed

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sdr3-planning#5]
This needs to be broken into actionable pieces, but for the sake of the overarching question, these are the points:

- Do we want versioning?
- What is that versioning?
- Where does it happen? Fedora or not?
- What is the scope of the object versioned?
- What have we learned from SDR2’s current approach?
- What from the above are the functional requirements from this for Hyku / Hyrax dev?

[source: [2017-07-08 SDR3 Planning Meeting](https://docs.google.com/document/d/1wt2hi6t1Ac8jMStG_egLCXBmJ86F7xBLqXAfaEaXtwE/edit#)]

**Comment by LynnMcRae** [comment]
To help understand what SDR2 has today, I moved all the historical versioning docs and placed a new summary of Repository versioning at https://consul.stanford.edu/display/chimera/DOR+and+SDR+object+versioning. Identifying improvement or areas of clarification welcome.
